---
upload_path: "/assets/images/uploads"
frontmatter_file_url_template: "/assets/images/uploads/:year:/:month:/:day:"
body_file_url_template: "/assets/images/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
collections: 
